// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CRDT Library",
    platforms: [
        .iOS("17.0"),
    ],
    products: [
        .library(
            name: "CRDT",
            targets: ["CRDT"]
        ),
        .iOSApplication(
            name: "CRDT Library",
            targets: ["TestApp"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .box),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/MutatingFunc/UnitTestingPreviews", "0.1.4"..<"1.0.0"),
    ],
    targets: [
        .target(
            name: "CRDT",
            dependencies: [
                .product(name: "UnitTestingPreviews", package: "UnitTestingPreviews")
            ]
        ),
        .executableTarget(
            name: "TestApp",
            dependencies: [
                "CRDT",
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        ),
    ]
)

for target in package.targets {
  target.swiftSettings = target.swiftSettings ?? []
  target.swiftSettings?.append(
    contentsOf: [
      .enableExperimentalFeature("StrictConcurrency")
    ]
  )
}